### ISSUE TITLE
Sizing textarea width

### ISSUE THREAD

**Issue by ghost** [vitalets/x-editable#361]
Is there a way for us to size a specific textarea width in a inline or popover edit mode?  Yet allowing the textarea to stretch if needed?

**Comment by Toilal** [comment]
This works for me

```css
.editable-wrap {
    display: block;
}

.editable-controls input {
  width: 100%;
}
```

This make all xeditable inputs take available width.

**Comment by imnzv** [comment]
Another solution: 

```
.editable-container.editable-inline,
.editable-container.editable-inline .control-group.form-group,
.editable-container.editable-inline .control-group.form-group .editable-input,
.editable-container.editable-inline .control-group.form-group .editable-input textarea,
.editable-container.editable-inline .control-group.form-group .editable-input select,
.editable-container.editable-inline .control-group.form-group .editable-input input:not([type=radio]):not([type=checkbox]):not([type=submit])
{
    width: 100%!important;
}

```

**Comment by lukaszbanasiak** [comment]
My solution:

    .editable-wrap {
      display: inline-block;
      white-space: nowrap;
      margin: 0;
      width: 100%;  //
    }
    .editable-wrap .editable-controls, .editable-wrap .editable-error {
      margin-bottom: 0;
      width: 100%;
    }
    .editable-wrap .editable-controls>select {
        margin-bottom: 0;
    }
    .editable-wrap .editable-controls>input, .editable-wrap .editable-controls>textarea {
      margin-bottom: 0;
      width: -moz-calc(100% - 76px);
      width: -webkit-calc(100% - 76px);
      width: calc(100% - 76px);
    }

**Comment by GreenOn** [comment]
@lukaszbanasiak. Thank you for posting your solution. It worked great!

**Comment by JustinCheong** [comment]
how do i make editable-wrap only apply to some input boxes?

**Comment by BrnoPCmaniak** [comment]
I merged @Relequestual JS with @ddctd143 HTML and added class to put everything inside and also modernize the CSS classes. I also added padding for buttons.

My complete solution if somebody would be interested:
CSS:
```css
/* bootstrap-xeditable occupy 100% of space */
.textarea_modal_widget .editable-container.editable-inline {
    display: inline;
}

.textarea_modal_widget .editable-input {
    display: inline;
}

.textarea_modal_widget .editableform .form-control {
    width: 100%;
}

.textarea_modal_widget .editable-buttons {
  padding-top: 10px;
}
```
JS:
```js
$('#comment').on('shown', function(e, editable) {
    $('.textarea_modal_widget .input-large').parents('form').removeClass('form-inline');
});
```
HTML: 
```html
<div class="textarea_modal_widget"><a href="#" id="comment" data-type="textarea" data-pk="1" ...>
SOMETHING LITTLE LONGER</a></div>
```
![x-editable](https://cloud.githubusercontent.com/assets/1249759/18178333/3637408a-707e-11e6-9237-3959e53c785e.png)
